name: gp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  carousel_slider:
  flutter_screenutil:
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  shared_preferences: ^2.5.3
  firebase_storage: ^12.4.6
  provider: ^6.1.5
  url_launcher: ^6.3.1


  image_picker: ^1.1.2
  geocoding: ^4.0.0
  location: ^5.0.3
  permission_handler: ^12.0.0+1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 700
